version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - TEST_MSG=Running in Docker!
      - ENVIRONMENT=development
    restart: unless-stopped
    container_name: jelastic-golang-hello

  # Alternative service using pre-built image (uncomment if needed)
  # app-image:
  #   image: jelastic-golang-hello:latest
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - PORT=3000
  #     - HOST=0.0.0.0
  #     - TEST_MSG=Running from pre-built image!
  #     - ENVIRONMENT=production
  #   restart: unless-stopped
  #   container_name: jelastic-golang-hello-image
