apiVersion: v1
kind: Service
metadata:
  name: {{ include "jelastic-golang-hello.fullname" . }}
  labels:
    {{- include "jelastic-golang-hello.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "jelastic-golang-hello.selectorLabels" . | nindent 4 }}

{{- if .Values.service.nodePort.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jelastic-golang-hello.fullname" . }}-nodeport
  labels:
    {{- include "jelastic-golang-hello.labels" . | nindent 4 }}
    service-type: nodeport
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "jelastic-golang-hello.selectorLabels" . | nindent 4 }}
{{- end }}

{{- if .Values.service.loadBalancer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jelastic-golang-hello.fullname" . }}-lb
  labels:
    {{- include "jelastic-golang-hello.labels" . | nindent 4 }}
    service-type: loadbalancer
  {{- with .Values.service.loadBalancer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "jelastic-golang-hello.selectorLabels" . | nindent 4 }}
{{- end }}