name: GitHub Action Runner Build

on:
  push:
    branches: [ main, http-only ]
permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Harbor variables
        run: |
          echo "HARBOR_REGISTRY=${{ env.HARBOR_REGISTRY }}"
          echo "HARBOR_USERNAME=${{ env.HARBOR_USERNAME }}"
          echo "HARBOR_PASSWORD=${{ env.HARBOR_PASSWORD }}"
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ env.HARBOR_REGISTRY }}
          username: ${{ env.HARBOR_USERNAME }}
          password: ${{ env.HARBOR_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,
          tags: ${{ env.HARBOR_REGISTRY }}/test/jelastic-golang-hello:latest
          cache-from: type=registry,ref=${{ env.HARBOR_REGISTRY }}/test/jelastic-golang-hello:buildcache
          cache-to: type=registry,ref=${{ env.HARBOR_REGISTRY }}/test/jelastic-golang-hello:buildcache,mode=max,ignore-error=true,image-manifest=true,oci-mediatypes=true

      - name: List docker images
        run: |
          docker images --all
